"""Add expense history and soft delete fields

Revision ID: 7c1df6657f25
Revises: 7bdbf75fcc04
Create Date: 2026-01-09 17:11:27.541441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1df6657f25'
down_revision = '7bdbf75fcc04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
